# Generated by Django 4.0.3 on 2022-07-19 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelA', models.CharField(max_length=10)),
                ('humedadS', models.CharField(max_length=10)),
                ('temperatura', models.CharField(max_length=10)),
                ('humedad', models.CharField(max_length=10)),
                ('riego', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
